Repository SovereignCloudStack/github-manager, pull requests merged in 2023-10, with the labels that each got.

#157 Add Nadja. Remove Ramona & Paul from OSISM. Mov MatFechner to wavecon.
  orgs/SovereignCloudStack/data.yaml
Labels: housekeeping

#158 Add Marc to SCS members and to SCS project org.
  orgs/SovereignCloudStack/data.yaml
Labels: housekeeping

#159 Protect v6.0.0 of k8s-capi repo
  orgs/SovereignCloudStack/repositories/k8s-cluster-api-provider.yml
Labels: Container

#145 Fix/no minery parent
  orgs/SovereignCloudStack/data.yaml
Labels: housekeeping

#165 Add manually created labels
  config.yaml
Labels: enhancement

#166 Add Michal to SCS members and to dNation, VP06c teams
  orgs/SovereignCloudStack/data.yaml
Labels: Container
