Repository SovereignCloudStack/github-manager, pull requests merged in 2023-08, with the labels that each got.

#137 Add Martin
  orgs/SovereignCloudStack/data.yaml
Labels: Community

#143 Add David and Miguel as SCS members w/ mineryreport.
  orgs/SovereignCloudStack/data.yaml
Labels: security

#148 Add @bitkeks (Dominik Pataky).
  orgs/SovereignCloudStack/data.yaml
Labels: housekeeping
