Repository SovereignCloudStack/github-manager, pull requests merged in 2024-05, with the labels that each got.

#257 Add Ilja Shmelkin to SCS Org, C&H, VP10.
  orgs/SovereignCloudStack/data.yaml
Labels: Community, SCS-VP10

#258 Add Artem Goncharov.
  orgs/SovereignCloudStack/data.yaml
Labels: housekeeping

#262 Adding Tomasz smado data into a data.yaml file
  orgs/SovereignCloudStack/data.yaml
Labels: SCS-VP12
